#!/usr/bin/env bash

install_apps() {
  local application_list=(
    "firefox"
    "pipewire-jack" # firefox
    "grim"          # screenshot
    "slurp"         # screenshot
    "satty"         # screenshot
    "spotify-launcher"
    "btop"
    "powertop"
    "mako"
    "nautilus"
    "fuzzel"
    "gimp"
    "libreoffice-still"
    "discord"
  )

  sudo pacman -S --noconfirm --needed "${application_list[@]}"
}

install_apps
