#!/usr/bin/env bash

install_waybar() {
  local dependencies=(
    "git"
    "base-devel"
    "gtkmm3"
    "jsoncpp"
    "libsigc++"
    "fmt"
    "wayland"
    "chrono-date"
    "spdlog"
    "libxkbcommon"
    "upower"
    "gtk3"
    "libpulse"
    "libnl"
    "libappindicator-gtk3"
    "libdbusmenu-gtk3"
    "libmpdclient"
    "sndio"
    "libevdev"
    "cmake"
    "meson"
    "scdoc"
    "wayland-protocols"
    "glib2-devel"
    "gobject-introspection"
    "libgirepository"
  )

  sudo pacman -S --noconfirm --needed "${dependencies[@]}"

  local downloads_folder="$HOME/Downloads"
  git clone https://github.com/Alexays/Waybar "$downloads_folder/waybar"
  pushd "$downloads_folder/waybar" || exit
  echo "meson setup build -Drfkill=enabled START"
  sleep 10
  meson setup build -Drfkill=enabled
  echo "meson setup build -Drfkill=enabled FINISHED"
  sleep 10
  echo "ninja -C build START"
  sleep 10
  ninja -C build
  echo "ninja -C build FINISHED"
  sleep 10
  echo "ninja -C build install START"
  sleep 10
  ninja -C build install
  echo " ninja -C build install FINISHED"
  sleep 10
  popd || exit
}

install_waybar
