#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed zsh
hash -r
echo "ID"
id
sleep 10
chsh -s $(which zsh)

sudo tee -a /etc/zsh/zshenv > /dev/null << 'EOF'
if [[ -z $XDG_CONFIG_HOME ]]; then
    export XDG_CONFIG_HOME="$HOME/.config"
fi

if [[ -d "$XDG_CONFIG_HOME/zsh" ]]; then
    export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
fi
EOF
